version: '3.8'

services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Narek100*
      POSTGRES_DB: movie_db
    ports:
      - "5432:5432"
    volumes:
      - db_data_volume_testing:/var/lib/postgresql/data

  app:
    build: .
    depends_on:
      - db
    ports:
      - "3000:3000"
    env_file:
      - .env
    environment:
      DB_HOST: "db"

    volumes:
      - .:/app
    command: sh -c "npm run migration:run && npm run start"

volumes:
  db_data_volume_testing:
